models_path: 'test-app/app/models'
serializers_path: 'test-app/app/serializers'
migrations_path: 'test-app/db/migrations'
associations_path: 'test-app/db/associations.ts'
schema_path: 'test-app/db/schema.ts'
db_config_path: 'test-app/conf/env/db.yml'
db_seed_path: 'test-app/db/seed.ts'
unit_spec_path: 'test-app/spec/unit'
feature_spec_path: 'test-app/spec/features'
dreamconf_path: 'test-app/conf/dreamconf'
