  export type RouteTypes =
    | '/ping'
  | '/auth'
  | '/auth-ping'
  | '/api-ping'
  | '/cast-param-test'
  | '/users-before-all-test'
  | '/failed-to-save-test'
  | '/force-throw'
  | '/conflict'
  | '/api/ping'
  | '/api/v1/ping'
  | '/api/v1/users'
  | '/api/users/:userId/pets'
  | '/api/users/:userId/pets/:id'
  | '/api/users'
  | '/api/users/:id'
  | '/scoped-things/testing-scopes'
  | '/login'
  | '/users/:id/hello'
  | '/users/:id/'
  | '/users'
  | '/greeter/hello'
  | '/greeter'
  | '/route-exists-but-controller-doesnt'
  | '/controller-exists-but-method-doesnt'
  