protocols:
  email:
    default:
      service: gmail
      auth:
        user: ENV::GMAIL_AUTH_USERNAME
        pass: ENV::GMAIL_AUTH_PASSWORD

  sms:
    default:
      adapter: twilio
      number: ENV::TWILIO_SMS_PHONE
      auth:
        sid: ENV::TWILIO_SID
        token: ENV::TWILIO_AUTH_TOKEN
