development:
  default:
    adapter: local

  remote:
    adapter: s3
    bucket: ENV::AWS_BUCKET
    region: ENV::AWS_REGION
    auth:
      access_key_id: ENV::AWS_ACCESS_KEY_ID
      secret_access_key: ENV::AWS_SECRET_ACCESS_KEY

test:
  default:
    adapter: local

  remote:
    adapter: s3
    bucket: ENV::AWS_BUCKET
    region: ENV::AWS_REGION
    auth:
      access_key_id: ENV::AWS_ACCESS_KEY_ID
      secret_access_key: ENV::AWS_SECRET_ACCESS_KEY

staging:
  default:
    adapter: local

  remote:
    adapter: s3
    bucket: ENV::AWS_BUCKET
    region: ENV::AWS_REGION
    auth:
      access_key_id: ENV::AWS_ACCESS_KEY_ID
      secret_access_key: ENV::AWS_SECRET_ACCESS_KEY

production:
  default:
    adapter: local

  remote:
    adapter: s3
    bucket: ENV::AWS_BUCKET
    region: ENV::AWS_REGION
    auth:
      access_key_id: ENV::AWS_ACCESS_KEY_ID
      secret_access_key: ENV::AWS_SECRET_ACCESS_KEY
