const apiRoutes = {
  // NOTE: this is autogenerated when you first provision a psychic app.
  // once you begin adding routes to your backend, run:
  //
  //    `yarn psy sync:client:routes`
  //
  // to rebuild this file with real routes
  placeholder: { path: 'placeholder', method: 'get' },
} as const

export default apiRoutes
