development:
  name: 'ENV::DB_NAME'
  username: 'ENV::DB_USERNAME'
  password: 'ENV::DB_PASSWORD'
  host: 'ENV::DB_HOST'
  port: 'ENV::DB_PORT'

staging:
  name: 'ENV::DB_NAME'
  username: 'ENV::DB_USERNAME'
  password: 'ENV::DB_PASSWORD'
  host: 'ENV::DB_HOST'
  port: 'ENV::DB_PORT'

test:
  name: 'ENV::DB_NAME'
  username: 'ENV::DB_USERNAME'
  password: 'ENV::DB_PASSWORD'
  host: 'ENV::DB_HOST'
  port: 'ENV::DB_PORT'

production:
  name: 'ENV::DB_NAME'
  username: 'ENV::DB_USERNAME'
  password: 'ENV::DB_PASSWORD'
  host: 'ENV::DB_HOST'
  port: 'ENV::DB_PORT'
