export {
  MissingControllerActionPairingInRoutes,
  type OpenapiContent,
  type OpenapiEndpointRendererOpts,
  type OpenapiEndpointResponse,
  type OpenapiHeaderOption,
  type OpenapiHeaders,
  type OpenapiHeaderType,
  type OpenapiMethodBody,
  type OpenapiParameterResponse,
  type OpenapiPathParams,
  type OpenapiQueryOption,
  type OpenapiResponses,
  type OpenapiSchema,
  type OpenapiPathParamOption as OpenapiUriOption,
} from '../openapi-renderer/endpoint.js'
