development:
  name: 'ENV::PSYCHIC_CORE_DB_NAME'
  username: 'ENV::PSYCHIC_CORE_DB_USERNAME'
  password: 'ENV::PSYCHIC_CORE_DB_PASSWORD'
  host: 'ENV::PSYCHIC_CORE_DB_HOST'
  port: 'ENV::PSYCHIC_CORE_DB_PORT'

staging:
  name: 'ENV::PSYCHIC_CORE_DB_NAME'
  username: 'ENV::PSYCHIC_CORE_DB_USERNAME'
  password: 'ENV::PSYCHIC_CORE_DB_PASSWORD'
  host: 'ENV::PSYCHIC_CORE_DB_HOST'
  port: 'ENV::PSYCHIC_CORE_DB_PORT'

test:
  name: 'ENV::PSYCHIC_CORE_DB_NAME'
  username: 'ENV::PSYCHIC_CORE_DB_USERNAME'
  password: 'ENV::PSYCHIC_CORE_DB_PASSWORD'
  host: 'ENV::PSYCHIC_CORE_DB_HOST'
  port: 'ENV::PSYCHIC_CORE_DB_PORT'

production:
  name: 'ENV::PSYCHIC_CORE_DB_NAME'
  username: 'ENV::PSYCHIC_CORE_DB_USERNAME'
  password: 'ENV::PSYCHIC_CORE_DB_PASSWORD'
  host: 'ENV::PSYCHIC_CORE_DB_HOST'
  port: 'ENV::PSYCHIC_CORE_DB_PORT'
