/*

                                    ,▄█▄                 
    ]█▄▄                         ╓█████▌                 
    ▐██████▄                   ▄█████▓╣█                 
     ║████████▄,  ,  ,,▄,▄▄▄▓██████╬╬╣╣▌                 
      ╚███╣██████████▓▓▓▓██████████╩╠╬▓                  
       ╙█╬╬╬▓███████████████████████▒▓▌                  
        ╙▓█▓██████████████████████████                   
         ╚██████▀███████████╩█▓▌▐▓████▄                  
         '║█████`╣█Γ║████████▄▄φ▓█████▌                 
          ║█████████████████████▓█████▌                  
           █████████████▓▓████████████                   
           ║█████████████████████████                    
          ]█████████████████████████                     
         ,▓██████████████████████████                    
        ▓█████████████████████████████µ                  
       ▐███████████████████████████████▄▄                
       ║█████████████████████████████████╬╬╣▓            
   ,╔╦║███████████████████████████████████▓╬╬╣           
,≥≥⌠░░░╠▓████████████████████████████████████▓▓          
,;=-',▄█████████████████████████████████████████▓        
                                                         
                                                         
                                                         
  ██████╗ ███████╗██╗   ██╗ ██████╗██╗  ██╗██╗ ██████╗   
  ██╔══██╗██╔════╝╚██╗ ██╔╝██╔════╝██║  ██║██║██╔════╝   
  ██████╔╝███████╗ ╚████╔╝ ██║     ███████║██║██║        
  ██╔═══╝ ╚════██║  ╚██╔╝  ██║     ██╔══██║██║██║        
  ██║     ███████║   ██║   ╚██████╗██║  ██║██║╚██████╗   
  ╚═╝     ╚══════╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝ ╚═════╝   
                                                         
                                                         

This file was automatically generated by my cat, Aster.
He does not want you mucking about with his files,
and we are pretty lax on trimming his nails.

I mean, we have him pretty well fenced in but he is an
escape artist and he still manages to get fleas!

My point is, don't go mucking about with his files!

He actually has a hopefully well-tempered message for
us humans, he says:

"
  Dear pathetic humans,

  Here is a haiku to keep you in line

  don't dare go mucking
  with my files, I lyke them fine
  prettierignore
"

*/

export const globalTypeConfig = {
  serializers: [
    'Admin/PetSerializer',
    'Admin/PetSummarySerializer',
    'Admin/UserSerializer',
    'Admin/UserSummarySerializer',
    'Admin/V2/PetSerializer',
    'Admin/V2/PetSummarySerializer',
    'Balloon/LatexSerializer',
    'Balloon/LatexSummarySerializer',
    'Balloon/MylarSerializer',
    'Balloon/MylarSummarySerializer',
    'BalloonSerializer',
    'BalloonSummarySerializer',
    'Circular/HelloSerializer',
    'Circular/WorldSerializer',
    'Comment1OnlyUsedInOneControllerSerializer',
    'Comment2OnlyUsedInOneControllerSerializer',
    'CommentSerializer',
    'CommentSummarySerializer',
    'CommentTestingAdditionalPropertiesSerializer',
    'CommentTestingAdditionalPropertiesShorthandSerializer',
    'CommentTestingBasicArraySerializerRefSerializer',
    'CommentTestingBasicSerializerRefSerializer',
    'CommentTestingDateSerializer',
    'CommentTestingDateTimeSerializer',
    'CommentTestingDecimalSerializer',
    'CommentTestingDecimalShorthandSerializer',
    'CommentTestingDefaultNullFieldsSerializer',
    'CommentTestingDefaultObjectFieldsSerializer',
    'CommentTestingIntegerSerializer',
    'CommentTestingIntegerShorthandSerializer',
    'CommentTestingObjectWithSerializerRefSerializer',
    'CommentTestingRootSerializerRefSerializer',
    'CommentTestingStringArraySerializer',
    'CommentTestingStringArrayShorthandSerializer',
    'CommentTestingStringSerializer',
    'CommentTestingStringShorthandSerializer',
    'CommentWithAllOfArraySerializer',
    'CommentWithAllOfObjectSerializer',
    'CommentWithAnyOfArraySerializer',
    'CommentWithAnyOfObjectSerializer',
    'CommentWithFlattenedUserSerializer',
    'CommentWithOneOfArraySerializer',
    'CommentWithOneOfObjectSerializer',
    'PetAdditionalSerializer',
    'PetSerializer',
    'PetSummarySerializer',
    'PetWithAssociationSerializer',
    'PetWithFavoriteTreatsOverrideSerializer',
    'PetWithFavoriteTreatsSerializer',
    'PetWithFlattenedAssociationSerializer',
    'PostSerializer',
    'PostSummarySerializer',
    'PostWithCommentsSerializer',
    'PostWithRecentCommentSerializer',
    'SimpleSerializerModelSerializer',
    'SimpleSerializerModelSummarySerializer',
    'UserExtraSerializer',
    'UserSerializer',
    'UserSummarySerializer',
    'UserWithFlattenedPostSerializer',
    'UserWithOptionalFlattenedPostSerializer',
    'UserWithPostsSerializer',
    'UserWithRecentPostSerializer',
    'ViewModels/MyViewModelSerializer',
    'ViewModels/MyViewModelSummarySerializer',
  ],
} as const
