/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface openapiPaths {
    "/api/pets": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pets/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success, no content */
                204: components["responses"]["NoContent"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        bio?: string;
                        /** Format: date */
                        birthdate?: string | null;
                        /** Format: date */
                        createdOn?: string;
                        email?: string;
                        favoriteBigint?: string | null;
                        favoriteBigints?: string[] | null;
                        favoriteBooleans?: boolean[] | null;
                        favoriteCitext?: string | null;
                        favoriteCitexts?: string[] | null;
                        favoriteDates?: string[] | null;
                        favoriteDatetimes?: string[] | null;
                        favoriteIntegers?: number[] | null;
                        favoriteJsonbs?: Record<string, never>[] | null;
                        favoriteJsons?: Record<string, never>[] | null;
                        favoriteNumerics?: number[] | null;
                        favoriteTexts?: string[] | null;
                        favoriteUuids?: string[] | null;
                        jsonData?: Record<string, never> | null;
                        jsonbData?: Record<string, never> | null;
                        name?: string | null;
                        nicknames?: string[] | null;
                        notes?: string | null;
                        optionalUuid?: string | null;
                        passwordDigest?: string;
                        requiredFavoriteBigint?: string;
                        requiredFavoriteBigints?: string[];
                        requiredFavoriteBooleans?: boolean[];
                        requiredFavoriteCitext?: string;
                        requiredFavoriteCitexts?: string[];
                        requiredFavoriteDates?: string[];
                        requiredFavoriteDatetimes?: string[];
                        requiredFavoriteIntegers?: number[];
                        requiredFavoriteJsonbs?: Record<string, never>[];
                        requiredFavoriteJsons?: Record<string, never>[];
                        requiredFavoriteNumerics?: number[];
                        requiredFavoriteTexts?: string[];
                        requiredFavoriteUuids?: string[];
                        requiredJsonData?: Record<string, never>;
                        requiredJsonbData?: Record<string, never>;
                        requiredNicknames?: string[];
                        uuid?: string;
                        password?: (string | null) | (number | null) | (Record<string, never> | null);
                        openapiVirtualSpecTest?: string | null;
                        openapiVirtualSpecTest2?: string[];
                    };
                };
            };
            responses: {
                /** @description Success, no content */
                204: components["responses"]["NoContent"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        bio?: string;
                        /** Format: date */
                        birthdate?: string | null;
                        /** Format: date */
                        createdOn?: string;
                        email?: string;
                        favoriteBigint?: string | null;
                        favoriteBigints?: string[] | null;
                        favoriteBooleans?: boolean[] | null;
                        favoriteCitext?: string | null;
                        favoriteCitexts?: string[] | null;
                        favoriteDates?: string[] | null;
                        favoriteDatetimes?: string[] | null;
                        favoriteIntegers?: number[] | null;
                        favoriteJsonbs?: Record<string, never>[] | null;
                        favoriteJsons?: Record<string, never>[] | null;
                        favoriteNumerics?: number[] | null;
                        favoriteTexts?: string[] | null;
                        favoriteUuids?: string[] | null;
                        jsonData?: Record<string, never> | null;
                        jsonbData?: Record<string, never> | null;
                        name?: string | null;
                        nicknames?: string[] | null;
                        notes?: string | null;
                        optionalUuid?: string | null;
                        passwordDigest?: string;
                        requiredFavoriteBigint?: string;
                        requiredFavoriteBigints?: string[];
                        requiredFavoriteBooleans?: boolean[];
                        requiredFavoriteCitext?: string;
                        requiredFavoriteCitexts?: string[];
                        requiredFavoriteDates?: string[];
                        requiredFavoriteDatetimes?: string[];
                        requiredFavoriteIntegers?: number[];
                        requiredFavoriteJsonbs?: Record<string, never>[];
                        requiredFavoriteJsons?: Record<string, never>[];
                        requiredFavoriteNumerics?: number[];
                        requiredFavoriteTexts?: string[];
                        requiredFavoriteUuids?: string[];
                        requiredJsonData?: Record<string, never>;
                        requiredJsonbData?: Record<string, never>;
                        requiredNicknames?: string[];
                        uuid?: string;
                        password?: (string | null) | (number | null) | (Record<string, never> | null);
                        openapiVirtualSpecTest?: string | null;
                        openapiVirtualSpecTest2?: string[];
                    };
                };
            };
            responses: {
                /** @description Success, no content */
                204: components["responses"]["NoContent"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        trace?: never;
    };
    "/balloons": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": (components["schemas"]["Latex"] | components["schemas"]["Mylar"])[];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balloons/index-different-dreams": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": (components["schemas"]["Latex"] | components["schemas"]["Mylar"] | components["schemas"]["Pet"])[];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balloons/index-dreams-and-view-model": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": (components["schemas"]["Latex"] | components["schemas"]["Mylar"] | components["schemas"]["MyViewModel"] | components["schemas"]["Pet"])[];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balloons/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Latex"] | components["schemas"]["Mylar"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/circular": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Hello"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/greeter/justforspecs": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentTestingBasicSerializerRef"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi-validation-on-explicit-query-arrays": {
        parameters: {
            query?: {
                /** @description myArray[] */
                "myArray[]"?: string[];
            };
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description myArray[] */
                    "myArray[]"?: string[];
                };
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success, no content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi-validation-on-explicit-query-arrays-without-brackets": {
        parameters: {
            query?: {
                /** @description myArray */
                myArray?: string[];
            };
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description myArray */
                    myArray?: string[];
                };
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success, no content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi-validation-test": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        howyadoin?: string | null;
                    };
                };
            };
            responses: {
                /** @description Success, no content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi/openapi-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        collarCount?: string | null;
                        collarCountInt?: number | null;
                        collarCountNumeric?: number | null;
                        favoriteTreats?: ("efishy feesh" | "snick snowcks" | null)[] | null;
                        /** Format: date-time */
                        lastHeardAt?: string;
                        /** Format: date-time */
                        lastSeenAt?: string | null;
                        likesTreats?: boolean;
                        likesWalks?: boolean | null;
                        name?: string | null;
                        nonNullFavoriteTreats?: ("efishy feesh" | "snick snowcks")[];
                        /** @enum {string} */
                        nonNullSpecies?: "cat" | "noncat";
                        requiredCollarCount?: string;
                        requiredCollarCountInt?: number;
                        requiredCollarCountNumeric?: number;
                        /** @enum {string|null} */
                        species?: "cat" | "noncat" | null;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        collarCount?: string | null;
                        collarCountInt?: number | null;
                        collarCountNumeric?: number | null;
                        favoriteTreats?: ("efishy feesh" | "snick snowcks" | null)[] | null;
                        /** Format: date-time */
                        lastHeardAt?: string;
                        /** Format: date-time */
                        lastSeenAt?: string | null;
                        likesTreats?: boolean;
                        likesWalks?: boolean | null;
                        name?: string | null;
                        nonNullFavoriteTreats?: ("efishy feesh" | "snick snowcks")[];
                        /** @enum {string} */
                        nonNullSpecies?: "cat" | "noncat";
                        requiredCollarCount?: string;
                        requiredCollarCountInt?: number;
                        requiredCollarCountNumeric?: number;
                        /** @enum {string|null} */
                        species?: "cat" | "noncat" | null;
                    };
                };
            };
            responses: {
                /** @description Success, no content */
                204: components["responses"]["NoContent"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        trace?: never;
    };
    "/pets/{id}/my-posts": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        body?: string | null;
                    };
                };
            };
            responses: {
                /** @description Success, no content */
                204: components["responses"]["NoContent"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserExtra"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        bio?: string;
                        /** Format: date */
                        birthdate?: string | null;
                        /** Format: date */
                        createdOn?: string;
                        email?: string;
                        favoriteBigint?: string | null;
                        favoriteBigints?: string[] | null;
                        favoriteBooleans?: boolean[] | null;
                        favoriteCitext?: string | null;
                        favoriteCitexts?: string[] | null;
                        favoriteDates?: string[] | null;
                        favoriteDatetimes?: string[] | null;
                        favoriteIntegers?: number[] | null;
                        favoriteJsonbs?: Record<string, never>[] | null;
                        favoriteJsons?: Record<string, never>[] | null;
                        favoriteNumerics?: number[] | null;
                        favoriteTexts?: string[] | null;
                        favoriteUuids?: string[] | null;
                        jsonData?: Record<string, never> | null;
                        jsonbData?: Record<string, never> | null;
                        name?: string | null;
                        nicknames?: string[] | null;
                        notes?: string | null;
                        optionalUuid?: string | null;
                        passwordDigest?: string;
                        requiredFavoriteBigint?: string;
                        requiredFavoriteBigints?: string[];
                        requiredFavoriteBooleans?: boolean[];
                        requiredFavoriteCitext?: string;
                        requiredFavoriteCitexts?: string[];
                        requiredFavoriteDates?: string[];
                        requiredFavoriteDatetimes?: string[];
                        requiredFavoriteIntegers?: number[];
                        requiredFavoriteJsonbs?: Record<string, never>[];
                        requiredFavoriteJsons?: Record<string, never>[];
                        requiredFavoriteNumerics?: number[];
                        requiredFavoriteTexts?: string[];
                        requiredFavoriteUuids?: string[];
                        requiredJsonData?: Record<string, never>;
                        requiredJsonbData?: Record<string, never>;
                        requiredNicknames?: string[];
                        uuid?: string;
                        password?: (string | null) | (number | null) | (Record<string, never> | null);
                        openapiVirtualSpecTest?: string | null;
                        openapiVirtualSpecTest2?: string[];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserExtra"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/paginated": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recordCount: number;
                            pageCount: number;
                            currentPage: number;
                            results: components["schemas"]["UserSummary"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path: {
                /** @description The ID of the User */
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path: {
                    /** @description The ID of the User */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserWithPosts"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path: {
                    /** @description The ID of the User */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success, no content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path: {
                    /** @description The ID of the User */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        bio?: string;
                        /** Format: date */
                        birthdate?: string | null;
                        /** Format: date */
                        createdOn?: string;
                        email?: string;
                        favoriteBigint?: string | null;
                        favoriteBigints?: string[] | null;
                        favoriteBooleans?: boolean[] | null;
                        favoriteCitext?: string | null;
                        favoriteCitexts?: string[] | null;
                        favoriteDates?: string[] | null;
                        favoriteDatetimes?: string[] | null;
                        favoriteIntegers?: number[] | null;
                        favoriteJsonbs?: Record<string, never>[] | null;
                        favoriteJsons?: Record<string, never>[] | null;
                        favoriteNumerics?: number[] | null;
                        favoriteTexts?: string[] | null;
                        favoriteUuids?: string[] | null;
                        jsonData?: Record<string, never> | null;
                        jsonbData?: Record<string, never> | null;
                        name?: string | null;
                        nicknames?: string[] | null;
                        notes?: string | null;
                        optionalUuid?: string | null;
                        passwordDigest?: string;
                        requiredFavoriteBigint?: string;
                        requiredFavoriteBigints?: string[];
                        requiredFavoriteBooleans?: boolean[];
                        requiredFavoriteCitext?: string;
                        requiredFavoriteCitexts?: string[];
                        requiredFavoriteDates?: string[];
                        requiredFavoriteDatetimes?: string[];
                        requiredFavoriteIntegers?: number[];
                        requiredFavoriteJsonbs?: Record<string, never>[];
                        requiredFavoriteJsons?: Record<string, never>[];
                        requiredFavoriteNumerics?: number[];
                        requiredFavoriteTexts?: string[];
                        requiredFavoriteUuids?: string[];
                        requiredJsonData?: Record<string, never>;
                        requiredJsonbData?: Record<string, never>;
                        requiredNicknames?: string[];
                        uuid?: string;
                        password?: (string | null) | (number | null) | (Record<string, never> | null);
                        openapiVirtualSpecTest?: string | null;
                        openapiVirtualSpecTest2?: string[];
                    };
                };
            };
            responses: {
                /** @description Success, no content */
                204: components["responses"]["NoContent"];
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        trace?: never;
    };
    "/users/{id}/justforspecs": {
        parameters: {
            query?: never;
            header: {
                /** @description custom header */
                "custom-header": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description custom header */
                    "custom-header": string;
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentTestingBasicSerializerRef"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                418: components["responses"]["CustomResponse"];
                422: components["responses"]["ValidationErrors"];
                490: components["responses"]["CustomResponse"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Comment: {
            id: string;
            body: string | null;
        };
        CommentTestingBasicSerializerRef: {
            howyadoin: components["schemas"]["CommentTestingDoubleShorthand"];
        };
        CommentTestingDoubleShorthand: {
            /** Format: double */
            howyadoin: number;
        };
        CustomSchema: string;
        Hello: {
            world: components["schemas"]["World"];
            id: number;
            email: string;
            name: string | null;
        };
        Latex: {
            id: string;
            /** @enum {string|null} */
            color: "blue" | "green" | "red" | null;
            latexOnlyAttr: string;
        };
        MyViewModel: {
            name: string;
            favoriteNumber: number;
        };
        Mylar: {
            id: string;
            /** @enum {string|null} */
            color: "blue" | "green" | "red" | null;
            mylarOnlyAttr: string;
        };
        Pet: {
            id: string;
            name: string | null;
        };
        Post: {
            id: string;
            body: string | null;
            explicitlyOmittedFromParamSafeColumns: string | null;
            comments: components["schemas"]["Comment"][];
        };
        PostWithComments: {
            id: string;
            body: string | null;
            comments: components["schemas"]["Comment"][];
        };
        User: {
            id: number;
            email: string;
            name: string | null;
        };
        UserExtra: {
            id: number;
            howyadoin: {
                name?: string;
                stuff?: string[];
                nestedStuff?: {
                    nested1?: boolean;
                    nested2?: number[];
                };
            };
            nicknames: string[] | null;
        };
        UserSummary: {
            id: number;
        };
        UserWithPosts: {
            id: number;
            posts: components["schemas"]["PostWithComments"][];
        };
        ValidationErrors: {
            errors?: {
                [key: string]: string[];
            };
        };
        World: {
            hello: components["schemas"]["Hello"];
        };
    };
    responses: {
        /** @description The request has succeeded, but there is no content to render */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description The server would not process the request due to something the server considered to be a client error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrors"];
            };
        };
        /** @description The request was not successful because it lacks valid authentication credentials for the requested resource */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Understood the request, but refused to process it */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description The specified resource was not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description The request failed because a conflict was detected with the given request params */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description The request failed to process due to validation errors with the provided values */
        ValidationErrors: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrors"];
            };
        };
        /** @description the server encountered an unexpected condition that prevented it from fulfilling the request */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description my custom response */
        CustomResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": string;
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
