name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  build:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist

  publish:
    needs: []
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
